---
- name: install prerequisites
  apt: package={{ item }} state=installed
  with_items:
  - '{{ apt_requirements }}'
  tags: [install]

- name: create user
  user: name={{ user_username }} comment={{ user_realname }} uid=1000 group={{ user_username }}
        groups=sudo append=yes shell=/usr/bin/zsh
  tags: [config]
  when: user_username is defined
