---
- name: upgrade Homebrew
  homebrew: update_homebrew=yes
  tags: [homebrew, install]

- name: install Homebrew requirements
  homebrew: name={{ item }} state=latest
  with_items: '{{ brew_requirements }}'
  tags: [homebrew, install]

- name: install Python 2.x requirements
  pip: name={{ item }} executable=/usr/local/bin/pip2
  with_items: '{{ pip2_requirements }}'
  tags: [python, pip, install]

- name: install Python 3.x requirements
  pip: name={{ item }} executable=/usr/local/bin/pip3
  with_items: '{{ pip3_requirements }}'
  tags: [python3, pip3, install]

- name: install Homebrew Cask requirements
  homebrew_cask: name={{ item }}
  with_items: '{{ cask_requirements }}'
  tags: [cask, install]

- name: install App Store requirements
  osx_mas: app_id={{ item.id }}
  with_items: '{{ mas_requirements }}'
  tags: [mas, install]

#- name: install App Store updates
#  osx_mas: upgrade_all=yes
#  tags: [mas, install]
